version: '2.1'
services:

  unbound:
    image: pedrogoncalvesk/mailcow-unbound:2.1
    build: ./services/mailcow-unbound
    restart: always
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.254
        aliases:
          - unbound

  mysql:
    image: pedrogoncalvesk/mailcow-mysql:1.0
    build: ./services/mailcow-mysql
    volumes:
      - mysql-vol-1:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.250
        aliases:
          - mysql

  redis:
    image: redis:alpine
    volumes:
      - redis-vol-1:/data/
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.249
        aliases:
          - redis

  clamd:
    image: pedrogoncalvesk/mailcow-clamd:2.1
    build: ./services/mailcow-clamd
    restart: always
    environment:
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd:
    image: pedrogoncalvesk/mailcow-rspamd:2.1
    build: ./services/mailcow-rspamd
    stop_grace_period: 30s
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - nginx
    volumes:
      - dkim-vol-1:/data/dkim
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    dns:
      - 172.22.1.254
    hostname: rspamd
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.253
        aliases:
          - rspamd

  php-fpm:
    image: pedrogoncalvesk/mailcow-phpfpm:2.1
    build: ./services/mailcow-phpfpm
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - redis
      - mysql
      - postfix
    links:
      - redis:redis-mailcow
      - mysql:mysql-mailcow
    volumes:
      - web-vol-1:/var/www/web:rw
      - dynmaps-vol-1:/var/www/dynmaps:rw
      - dkim-vol-1:/data/dkim
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - POP_PORT=${POP_PORT:-110}
      - POPS_PORT=${POPS_PORT:-995}
      - SIEVE_PORT=${SIEVE_PORT:-4190}
      - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
      - SMTPS_PORT=${SMTPS_PORT:-465}
      - SMTP_PORT=${SMTP_PORT:-25}
      - DOCKERAPI_PORT=${DOCKERAPI_PORT:-8080}
      - DOCKERAPI_BIND=${DOCKERAPI_BIND:-0.0.0.0}
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        aliases:
          - phpfpm

  sogo:
    image: pedrogoncalvesk/mailcow-sogo:2.1
    build: ./services/mailcow-sogo
    links:
      - mysql
      - redis:redis-mailcow
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - TZ=${TZ}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.252
        aliases:
          - sogo

  nginx:
    image: pedrogoncalvesk/mailcow-nginx:1.1
    build: ./services/mailcow-nginx
    depends_on:
      - sogo
      - redis
      - php-fpm
    links:
      - sogo
      - redis
      - php-fpm:phpfpm
    environment:
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - HTTP_PORT=${HTTP_PORT:-80}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    volumes:
      - acme-vol-1:/acme:rw
      - web-vol-1:/web:rw
      - dynmaps-vol-1:/dynmaps:ro
      - ssl-vol-1:/etc/ssl/mail/:ro
    ports:
      - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.251
        aliases:
          - nginx

  dovecot:
    image: pedrogoncalvesk/mailcow-dovecot:2.1
    build: ./services/mailcow-dovecot
    links:
      - redis:redis-mailcow
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ssl-vol-1:/etc/ssl/mail/:ro
      - vmail-vol-1:/var/vmail
      - crypt-vol-1:/mail_crypt/
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    ports:
      - "${DOVEADM_PORT:-127.0.0.1:19991}:12345"
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
      - "${SIEVE_PORT:-4190}:4190"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    dns:
      - 172.22.1.254
    hostname: ${MAILCOW_HOSTNAME}
    networks:
      mailcow-network:
        aliases:
          - dovecot

  postfix:
    image: pedrogoncalvesk/mailcow-postfix:2.1
    build: ./services/mailcow-postfix
    links:
      - redis:redis-mailcow
    volumes:
      - ssl-vol-1:/etc/ssl/mail/:ro
      - postfix-vol-1:/var/spool/postfix
      - crypt-vol-1:/var/lib/zeyple
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    ports:
      - "${SMTP_PORT:-25}:25"
      - "${SMTPS_PORT:-465}:465"
      - "${SUBMISSION_PORT:-587}:587"
    restart: always
    dns:
      - 172.22.1.254
    hostname: ${MAILCOW_HOSTNAME}
    networks:
      mailcow-network:
        aliases:
          - postfix

  memcached:
    image: memcached:alpine
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        aliases:
          - memcached

  acme:
    image: pedrogoncalvesk/mailcow-acme:2.3
    build: ./services/mailcow-acme
    depends_on:
      - nginx
      - mysql
    links: 
      - mysql:mysql-mailcow
      - dockerapi
    environment:
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
      - DOCKERAPI_PORT=${DOCKERAPI_PORT:-8080}
      - DOCKERAPI_BIND=${DOCKERAPI_BIND:-0.0.0.0}
    volumes:
      - acme-vol-1:/var/www/acme:rw
      - ssl-vol-1:/var/lib/acme/:rw
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.247
        aliases:
          - acme

  fail2ban:
    image: pedrogoncalvesk/mailcow-fail2ban:2.1
    build: ./services/mailcow-fail2ban
    depends_on:
      - dovecot
      - postfix
      - sogo
      - php-fpm
      - redis
    restart: always
    stop_grace_period: 30s
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
    environment:
      - TZ=${TZ}
      - SKIP_FAIL2BAN=${SKIP_FAIL2BAN:-n}
    dns:
      - 172.22.1.254
    network_mode: "host"
    

  watchdog:
    image: pedrogoncalvesk/mailcow-watchdog:2.1
    build: ./services/mailcow-watchdog
    links:
      - dockerapi:dockerapi-mailcow
    volumes:
      - vmail-vol-1:/vmail:ro
    restart: always
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - USE_WATCHDOG=${USE_WATCHDOG:-n}
      - WATCHDOG_NOTIFY_EMAIL=${WATCHDOG_NOTIFY_EMAIL}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - DOCKERAPI_PORT=${DOCKERAPI_PORT:-8080}
      - DOCKERAPI_BIND=${DOCKERAPI_BIND:-0.0.0.0}
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.248
        aliases:
          - watchdog

  dockerapi:
    image: pedrogoncalvesk/mailcow-dockerapi:2.1
    build: ./services/mailcow-dockerapi
    oom_score_adj: -10
    environment:
      - DOCKERAPI_PORT=${DOCKERAPI_PORT:-8080}
      - DOCKERAPI_BIND=${DOCKERAPI_BIND:-0.0.0.0}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.246
        aliases:
          - dockerapi

  ipv6nat:
    image: robbertkl/ipv6nat
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  mailcow-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
        - subnet: fd4d:6169:6c63:6f77::/64

volumes:
  vmail-vol-1:
  mysql-vol-1:
  dkim-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  postfix-vol-1:
  crypt-vol-1:
  ssl-vol-1:
  dynmaps-vol-1:
  web-vol-1:
  acme-vol-1:
